### PR TITLE
#38 add global theme

### LINKED ISSUE #38: Client: Add a global theme
To style components (e.g. the color of a textfield) you need a custom theme (it is not possible to style it with scss).
This theme should be global, so that every component can use it.

### LINKED ISSUE #52: Client: Link highlighting does not work
When an user clicks on a sublink of "Mitglieder" like "Gesamtübersicht" the "Mitglieder" link will not be highlighted in the Drawer Component

### PR DESCRIPTION
**Pull request by LennartRukower**
Added a global theme and converted the scss-styling of the different components to css-in-ts-styling.
Closes #38 
Closes #52

### CODE REVIEW

File: client/src/index.tsx [hunk 1]
```diff
@@ -1,7 +1,30 @@
 import React from "react";
 import ReactDOM from "react-dom";
 import App from "./ts/global/App";
-
+import { ThemeProvider, createMuiTheme } from "@material-ui/core/styles";
 import "./scss/app.scss";
 
-ReactDOM.render(<App />, document.getElementById("root"));
+// Global theme
+export const globalTheme = createMuiTheme({
```
Comment (christophtrybek) [inline client/src/index.tsx:8]: Create separate component which should be imported here

File: client/src/ts/global/navigation/MenuDrawer.tsx [hunk 2]
```diff
@@ -33,229 +33,272 @@ import {
...
+  },
+}));
 
-    /**
-     * A drawer which enters from the left and depicts various options for navigation
-     * @param props
-     */
-    const MenuDrawer: React.FunctionComponent<DrawerProps> = (props: DrawerProps) => {
-      const location = useLocation();
+  // Interface for the drawer props
```
Comment (christophtrybek) [inline client/src/ts/global/navigation/MenuDrawer.tsx:80]: Remove spacing

File: client/src/ts/global/GlobalTheme.tsx [hunk 3]
```diff
@@ -0,0 +1,24 @@
+/**
+ * Contains the global styling of the components
+ */
+import { createMuiTheme } from "@material-ui/core/styles";
+
+// Global theme
+const globalTheme = createMuiTheme({
```
Comment (christophtrybek) [inline client/src/ts/global/GlobalTheme.tsx:7]: * Since the style definition is not a component consider moving it to ../utils
* Rename it to globalTheme.ts (camel case)

File: client/src/ts/global/navigation/MenuDrawer.tsx [hunk 4]
```diff
@@ -35,241 +35,287 @@ import {
   ExitToApp,
   TrendingUp
 } from "@material-ui/icons";
+import { 
+  makeStyles, 
+  createStyles, 
+  Theme } 
+from "@material-ui/core/styles";
```
Comment (qnewald) [inline client/src/ts/global/navigation/MenuDrawer.tsx:42]: Remove trailing whitespaces

Comment (qnewald) [reply client/src/ts/global/navigation/MenuDrawer.tsx:42]: Bracket after "Theme" should be in new line

File: client/src/ts/global/navigation/MenuDrawer.tsx [hunk 5]
```diff
@@ -35,241 +35,287 @@ import {
...
-      useEffect(() => {
-        setActiveNavLink(location.pathname);
-      }, [location.pathname]);
+// Interface for the drawer props
+interface DrawerProps {
+  drawer: (open: boolean) => (
+          event: React.KeyboardEvent | React.MouseEvent
+          ) => void;
+}
+/**
```
Comment (qnewald) [inline client/src/ts/global/navigation/MenuDrawer.tsx:93]: Add a blank line before multiline documentation
